### ISSUE TITLE
PostSpawnOrbit, Gobek, and The Sun

### ISSUE THREAD

**Issue by DeltaDizzy** [KSP-DDR/Terras-Ignotas#10]
Should we PostSpawnOrbit the Sun to orbit Gobek? If we do, what do we put for Gobek's referenceBody in Orbit?

**Comment by Mrcarrot1** [comment]
Just make Gobek the Sun and make a clone of the Sun to orbit it. That's what most interstellar mods with black hole galaxy centers do, and it works just fine.

**Comment by DeltaDizzy** [comment]
Alright then. Should be up on here later today for testing purposes.

**Comment by DeltaDizzy** [comment]
Ok, does KopernicusConfigs/Kerbol.cfg look alright? @Mrcarrot1

**Comment by Mrcarrot1** [comment]
You'll need an orbit node, and I'd prefer it not be Kerbol, but it looks good otherwise

**Comment by DeltaDizzy** [comment]
ah yes. You're better at this kind of thing than me, so  I'll let you take over from here.

**Comment by DeltaDizzy** [comment]
@Mrcarrot1 I forgot how things are going in this department, so is it ready for me to check it off the list?

**Comment by Mrcarrot1** [comment]
The MM patches for the stock system should work fine, but I'm going to change it a little to make it compatible with every planet pack that still has Kerbin orbiting the Sun.
